site_name: Help Pages
site_url: https://ise-efs-help-pages-mkdocs.netlify.com/

nav:
    - Home: index.md
    - ex: ex.md
    - Availability: Availability.md
    - GroupFilter: GroupFilter.md
    - MapsView: MapsView.md
    - SettingsHome: SettingsHome.md
    - Violations: Violations.md
    - Welcome: Welcome.md

extra_css: [extra.css]

repo_name: 'danielopdahl/ise-efs-help-pages-mkdocs'
repo_url: 'https://github.com/danielopdahl/ise-efs-help-pages-mkdocs'
